### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by nathanurwin** [nathanurwin/cookiecutter-git#15]

**Comment by slurdge** [comment]
You can use the requests package (i did on [my fork](https://github.com/slurdge/cookiecutter-git/commit/f1ac064e14668bdd3c87808e2dac6039b99f71c6)). I believe it would solve both python2 and python3 problems

**Comment by tuxredux** [comment]
Hey @slurdge :wave: 

[As you can see here](https://github.com/tuxredux/cookiecutter-git/issues/10#issuecomment-289101262), one of the goals of this project is to use only builtin libraries. You bring up a good point though. I think a good compromise would be using requests for python3, and possibly the requests urllib wrapper for a python2 fallback.

Thanks for your interest in cookiecutter-git!
