### ISSUE TITLE
Bitbucket remote repo failed

### ISSUE THREAD

**Issue by OksanaShc** [nathanurwin/cookiecutter-git#20]
After input of password to  my account from command line I received exception:

Traceback (most recent call last):
  File "/tmp/tmpr61y4z6r.py", line 203, in <module>
    main()
  File "/tmp/tmpr61y4z6r.py", line 198, in main
    setup_git_repo()
  File "/tmp/tmpr61y4z6r.py", line 129, in setup_git_repo
    auth_base = base64.b64encode('{}:{}'.format(*auth_info))
  File "/home/oshcherbyna/PycharmProjects/test_venv/lib/python3.6/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'
Stopping generation because post_gen_project hook script didn't exit successfully

**Comment by nathanurwin** [comment]
Hey @OksanaShc :wave: 

I appreciate the feedback! I need to integrate continuous integration testing (see #8 and #9), but I'll manually test Bitbucket and get that working today. I only use GitHub and GitLab myself, so apologies for the slight overlook. :sweat_smile: 

Thanks for your interest in cookiecutter-git! :slightly_smiling_face:

**Comment by OksanaShc** [comment]
Hey @nathanurwin !
I guess that it will be a problem with Python versions. I used 3.6.4. Is it supported?

**Comment by nathanurwin** [comment]
I thought it was only a Bitbucket thing, but you were right it was a Python 3 error! Manually testing takes some time and is not all comprehensive, but both Bitbucket and Python 3 should be working now (I'm going to push the release here in a minute). Thank you for your time! :+1:

**Comment by OksanaShc** [comment]
thank you too for your work and quick fix!
